var trackCards = [{"Card Number":null,"Type":"Checkpoint","Name":"Asteroid Belt","Distance":4,"Special":1,"Environmental Effect":"B -1 per round.  Ignore if M>3"},
{"Card Number":null,"Type":"Checkpoint","Name":"Binary System","Distance":4,"Special":1,"Environmental Effect":"B -1 per round. Ignore if E>3"},
{"Card Number":null,"Type":"Checkpoint","Name":"Black Hole","Distance":6,"Special":1,"Environmental Effect":"Time Dilation.  Take another turn."},
{"Card Number":null,"Type":"Checkpoint","Name":"Gas Giant","Distance":4,"Special":1,"Environmental Effect":"M -1 per round. Ignore if B>3"},
{"Card Number":null,"Type":"Checkpoint","Name":"Gravity Assist","Distance":5,"Special":1,"Environmental Effect":"E +1 "},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":2,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":3,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":4,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":5,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":6,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":2,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":3,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":4,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":5,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Open Space","Distance":6,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Checkpoint","Name":"Pirate System","Distance":5,"Special":1,"Environmental Effect":"Discard 1 random card from your hand (does not repeat).  Ignore if E>3"},
{"Card Number":null,"Type":"Checkpoint","Name":"Pulsar","Distance":3,"Special":1,"Environmental Effect":"E -1 per round. Ignore if S>2"},
{"Card Number":null,"Type":"Checkpoint","Name":"Special","Distance":2,"Special":1,"Environmental Effect":"Don't know yet."},
{"Card Number":null,"Type":"Checkpoint","Name":"Special","Distance":6,"Special":1,"Environmental Effect":"Don't know yet."},
{"Card Number":null,"Type":"Checkpoint","Name":"Thin Spacetime","Distance":4,"Special":1,"Environmental Effect":"Swap E and B values while on this leg."},
{"Card Number":null,"Type":"Special","Name":"Finish","Distance":4,"Special":0,"Environmental Effect":""},
{"Card Number":null,"Type":"Special","Name":"Lap","Distance":4,"Special":0,"Environmental Effect":"4 lap race"},
{"Card Number":null,"Type":"Special","Name":"Lap","Distance":4,"Special":0,"Environmental Effect":"2 lap race"},
{"Card Number":null,"Type":"Special","Name":"Lap","Distance":4,"Special":0,"Environmental Effect":"3 lap race"},
{"Card Number":null,"Type":"Special","Name":"Start","Distance":4,"Special":0,"Environmental Effect":""}]